# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: publish

on:
  push:
    branches: [ "nuget" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3.0.3
      with:
        dotnet-version: |
          6.0.x
          7.0.x
      
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: |
        dotnet build ./src/PddOpenSdk/PddOpenSdk.csproj --no-restore
        dotnet build ./src/AspNetCore/PddOpenSdk.AspNetCore.csproj --no-restore
        
    - name: Pack
      run: |
        dotnet pack ./src/PddOpenSdk/PddOpenSdk.csproj -o ./pack
        dotnet pack ./src/AspNetCore/PddOpenSdk.AspNetCore.csproj -o ./pack
        
    - name: Publish to Nuget
      run: |
        dotnet nuget push ./pack/ -k ${{ vars.NUGET_KEY }} --source https://api.nuget.org/v3/index.json
      # dotnet nuget push ./pack/ -k ${{ vars.PAT }} --source https://nuget.pkg.github.com/niltor/index.json
        
